language: csharp
solution: BeeCloud.sln
install:
  - nuget restore BeeCloud.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BeeCloud.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./BeeCloudTest/bin/Release/BeeCloudTest.dll